package loctag.actions;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import loctag.DTO.AnnotationDTO;
import loctag.constants.WS;
import loctag.util.HTTP;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.google.gson.Gson;


/**
 * Struts Action that handles requests for submitting an annotation
 */

public class SubmitAnnotationAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) {

		ActionForward forward = new ActionForward();

		//extract all fields from the request object
		int userID = Integer.valueOf(request.getSession().getAttribute("userID").toString());
		int categoryID = Integer.valueOf(request.getParameter("categoryID"));
		String title = request.getParameter("title");
		String description = request.getParameter("description");
	    double lat = Double.valueOf(request.getParameter("lat"));
	    double lon = Double.valueOf(request.getParameter("lon"));
	    String address = request.getParameter("autoAddress");
	    String picture = request.getParameter("picture");
	    String target = request.getParameter("target");
	    String eDate = request.getParameter("ADate");
	    			
	
		//construct an annotation DTO (leaving the date field blank because it's generated by the server
		AnnotationDTO annotationDTO = new AnnotationDTO(title, description, picture, userID, categoryID, "", lat, lon, address,target,eDate);

		//convert it to JSON
		Gson gson = new Gson();
  		String jsonAnnotation = gson.toJson(annotationDTO);
  		String ack=""; 		

		//perform HTTP POST
		try {
			String newAnnotationURL = WS.ENDPOINT_annotations;
			ack = HTTP.postHttpURL(newAnnotationURL,jsonAnnotation);
	  		System.out.println(ack);

		} catch (IOException e) {
			e.printStackTrace();
		}
  		

		//forward to jsp page of the new annotation
  		forward.setPath("annotation.do?id="+ack);
		forward.setRedirect(true);
		return forward;	
		
	}
}

