package loctag.actions;

import java.io.IOException;
import javax.servlet.http.*;
import loctag.DTO.AnnotationDTO;
import loctag.constants.WS;
import loctag.util.HTTP;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.google.gson.Gson;


/**
 * Struts Action that handles requests for updating an annotation's details
 */
public class UpdateDetailsAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {


		//extract all fields from the request object
		
		String annotationID = request.getParameter("annotationid");
		
		String ownerID = request.getParameter("ownerid");
		
		String title=request.getParameter("title");
		
		int categoryID = Integer.valueOf(request.getParameter("categoryID"));
						
		String address=request.getParameter("address");
		
		String description=request.getParameter("description");
		
		String target=request.getParameter("target");
		
		String ADate=request.getParameter("ADate");
		
		String userID = request.getSession().getAttribute("userID").toString();
		
		
		if (ownerID.equals(userID)) {

			//construct an annotation DTO (leaving the date field blank because it's generated by the server
			AnnotationDTO annotationDTO = new AnnotationDTO();
			annotationDTO.setTitle(title);
			annotationDTO.setCategoryID(categoryID);
			annotationDTO.setAddress(address);
			annotationDTO.setDescription(description);
			annotationDTO.setTarget(target);
			annotationDTO.seteDate(ADate);
			
			
			//convert it to JSON
			Gson gson = new Gson();
	  		String annotationDetails = gson.toJson(annotationDTO);
			
			
			//perform HTTP PUT
	  		try {
			String updateDetailsURL = WS.ENDPOINT_updatedetails+annotationID;
			String ack = HTTP.putHttpURL(updateDetailsURL,annotationDetails);
	  		System.out.println(ack);
			
			

		} catch (IOException e) {
			e.printStackTrace();
		}
  		
		}
  		
		//forward to jsp page of the updated annotation
		ActionForward forward = new ActionForward();
		forward.setPath("annotation.do?id="+annotationID);
		forward.setRedirect(true);
		return forward;		
	}
}
